flowchart TD
  HEADER(["Приём заказа"])
  n4["Оформить"]
  n5["Отказ"]
  n6["Закрыть"]
  n1(["КОНЕЦ"])
  n10["Принять заказ"]
  n20{"Товар в наличии?"}
  n30["Оформить доставку"]
  n50["Предложить альтернативу"]
  n60["Отменить заявку"]
  n80["Отправить уведомление"]
  n4 --> n10
  n5 --> n50
  n6 --> n80
  n10 --> n20
  n20 -- Да --> n30
  n20 -- Нет --> n5
  n30 --> n6
  n50 --> n60
  n60 --> n6
  n80 --> n1
  HEADER --> n4
